-- MySQL Script generated by MySQL Workbench
-- чт, 28-гру-2017 20:25:47 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema printer_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `printer_db` ;

-- -----------------------------------------------------
-- Schema printer_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `printer_db` DEFAULT CHARACTER SET utf8 ;
USE `printer_db` ;

-- -----------------------------------------------------
-- Table `printer_db`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`brand` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`brand` (
  `id` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`function_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`function_type` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`function_type` (
  `id` INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`user` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(40) NOT NULL,
  `is_admin` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`order` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`order` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cost` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `status` INT(1) UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `ordercol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `printer_db`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`print_resolution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`print_resolution` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`print_resolution` (
  `x` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `y` INT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`x`, `y`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`print_size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`print_size` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`print_size` (
  `id` INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`printing_technology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`printing_technology` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`printing_technology` (
  `id` INT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(55) NOT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`printer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`printer` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`printer` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `page_per_minute` FLOAT(32) UNSIGNED NOT NULL,
  `size` VARCHAR(45) NULL DEFAULT NULL,
  `weight` FLOAT(32) NULL DEFAULT NULL,
  `additional_info` TEXT NULL DEFAULT NULL,
  `amount` INT(4) UNSIGNED NOT NULL,
  `price` INT(10) UNSIGNED NOT NULL,
  `brand_id` INT(10) UNSIGNED NOT NULL,
  `function_type_id` INT(10) UNSIGNED NOT NULL,
  `printing_technology_id` INT(10) UNSIGNED NOT NULL,
  `print_size_id` INT UNSIGNED NOT NULL,
  `print_resolution_x` INT(10) UNSIGNED NOT NULL,
  `print_resolution_y` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `fk_printer_brand1_idx` (`brand_id` ASC),
  INDEX `fk_printer_function_type1_idx` (`function_type_id` ASC),
  INDEX `fk_printer_print_size1_idx` (`print_size_id` ASC),
  INDEX `fk_printer_print_resolution1_idx` (`print_resolution_x` ASC, `print_resolution_y` ASC),
  INDEX `fk_printer_printing_technology1_idx` (`printing_technology_id` ASC),
  CONSTRAINT `fk_printer_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `printer_db`.`brand` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_printer_function_type1`
    FOREIGN KEY (`function_type_id`)
    REFERENCES `printer_db`.`function_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_printer_print_size1`
    FOREIGN KEY (`print_size_id`)
    REFERENCES `printer_db`.`print_size` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_printer_print_resolution1`
    FOREIGN KEY (`print_resolution_x` , `print_resolution_y`)
    REFERENCES `printer_db`.`print_resolution` (`x` , `y`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_printer_printing_technology1`
    FOREIGN KEY (`printing_technology_id`)
    REFERENCES `printer_db`.`printing_technology` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`order_has_printer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`order_has_printer` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`order_has_printer` (
  `order_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `printer_id` INT(10) UNSIGNED NOT NULL,
  `amount` INT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`, `printer_id`),
  INDEX `fk_order_has_printer_printer1_idx` (`printer_id` ASC),
  INDEX `fk_order_has_printer_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_has_printer_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `printer_db`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_has_printer_printer1`
    FOREIGN KEY (`printer_id`)
    REFERENCES `printer_db`.`printer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `printer_db`;

DELIMITER $$

USE `printer_db`$$
DROP TRIGGER IF EXISTS `printer_db`.`order_has_printer_AFTER_INSERT` $$
USE `printer_db`$$
CREATE DEFINER = CURRENT_USER TRIGGER `printer_db`.`order_has_printer_AFTER_INSERT` AFTER INSERT ON `order_has_printer` FOR EACH ROW
BEGIN
	UPDATE `order`
           SET cost = cost + NEW.amount * (SELECT price FROM printer WHERE id=NEW.printer_id)
           WHERE id = NEW.order_id;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
