-- MySQL Script generated by MySQL Workbench
-- пт, 06-жов-2017 00:23:24 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema printer_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `printer_db` ;

-- -----------------------------------------------------
-- Schema printer_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `printer_db` DEFAULT CHARACTER SET latin1 ;
USE `printer_db` ;

-- -----------------------------------------------------
-- Table `printer_db`.`brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`brands` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`brands` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`connectivity_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`connectivity_types` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`connectivity_types` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`function_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`function_types` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`function_types` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`print_resolutions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`print_resolutions` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`print_resolutions` (
  `x` INT(10) UNSIGNED NOT NULL,
  `y` INT(10) UNSIGNED NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`print_sizes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`print_sizes` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`print_sizes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`printer_connectivity_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`printer_connectivity_type` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`printer_connectivity_type` (
  `printer_id` INT(10) UNSIGNED NOT NULL,
  `connectivity_type_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`printer_id`, `connectivity_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`printers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`printers` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`printers` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  `page_per_minute` INT(10) UNSIGNED NOT NULL,
  `brand_id` INT(10) UNSIGNED NOT NULL,
  `printing_technology_id` INT(10) UNSIGNED NOT NULL,
  `function_type_id` INT(10) UNSIGNED NOT NULL,
  `print_size_id` INT(10) UNSIGNED NOT NULL,
  `print_resolution_x` INT(10) UNSIGNED NOT NULL,
  `print_resolution_y` INT(10) UNSIGNED NOT NULL,
  `size` VARCHAR(16) NULL DEFAULT NULL,
  `weight` VARCHAR(16) NULL DEFAULT NULL,
  `additional_info` VARCHAR(500) NULL DEFAULT NULL,
  `number` INT(10) UNSIGNED NOT NULL,
  `price` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`printing_technologies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`printing_technologies` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`printing_technologies` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `printer_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`users` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(40) NOT NULL,
  `is_admin` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
