-- MySQL Script generated by MySQL Workbench
-- вт, 03-жов-2017 13:41:59 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema printer_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `printer_db` ;

-- -----------------------------------------------------
-- Schema printer_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `printer_db` DEFAULT CHARACTER SET utf8 ;
USE `printer_db` ;

-- -----------------------------------------------------
-- Table `printer_db`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`brand` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `printer_db`.`printing_technology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`printing_technology` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`printing_technology` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `printer_db`.`function_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`function_type` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`function_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `printer_db`.`print_size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`print_size` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`print_size` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `printer_db`.`print_resolution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`print_resolution` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`print_resolution` (
  `x` INT NOT NULL,
  `y` INT NOT NULL,
  PRIMARY KEY (`x`, `y`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `printer_db`.`printer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`printer` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`printer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `pages_per_minute` SMALLINT NULL,
  `brand_id` INT NOT NULL,
  `printing_technology_id` INT NOT NULL,
  `function_type_id` INT NOT NULL,
  `print_size_id` INT NOT NULL,
  `print_resolution_id` INT NOT NULL,
  `size` VARCHAR(16) NULL,
  `weight` VARCHAR(16) NULL,
  `description` VARCHAR(2000) NULL,
  `additional_info` VARCHAR(500) NULL,
  `number` INT(8) NOT NULL,
  `price` INT(8) NOT NULL,
  `print_resolution_x` INT NOT NULL,
  `print_resolution_y` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_printer_brand_idx` (`brand_id` ASC),
  INDEX `fk_printer_printing_technology1_idx` (`printing_technology_id` ASC),
  INDEX `fk_printer_function_type1_idx` (`function_type_id` ASC),
  INDEX `fk_printer_print_size1_idx` (`print_size_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_printer_print_resolution1_idx` (`print_resolution_x` ASC, `print_resolution_y` ASC))
ENGINE = MEMORY;


-- -----------------------------------------------------
-- Table `printer_db`.`connectivity_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`connectivity_type` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`connectivity_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`value` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `printer_db`.`printer_has_connectivity_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`printer_has_connectivity_type` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`printer_has_connectivity_type` (
  `printer_id` INT NOT NULL AUTO_INCREMENT,
  `connectivity_type_id` INT NOT NULL,
  PRIMARY KEY (`printer_id`, `connectivity_type_id`),
  INDEX `fk_printer_has_connectivity_type_connectivity_type1_idx` (`connectivity_type_id` ASC),
  INDEX `fk_printer_has_connectivity_type_printer1_idx` (`printer_id` ASC))
ENGINE = MEMORY;


-- -----------------------------------------------------
-- Table `printer_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `printer_db`.`user` ;

CREATE TABLE IF NOT EXISTS `printer_db`.`user` (
  `name` VARCHAR(16) NOT NULL,
  `email` VARCHAR(50) NULL,
  `password` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `is_admin` TINYINT(1) NULL DEFAULT 0,
  `uuid` VARCHAR(200) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
